version: '3.8'
services:
  web:
    build: .
    ports:
      - "3007:80"
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    external: true  # 连接到 1panel 创建的网络
    name: 1panel_default  # 使用 1panel 的默认网络名称